export const STORE_PERSONAL_DETAILS = "STORE_PERSONAL_DETAILS";
export const STORE_EDUCATION_DETAILS = "STORE_EDUCATION_DETAILS";
export const STORE_PROJECT_DETAILS = "STORE_PROJECT_DETAILS";
export const STORE_EXPERIANCE_DETAILS = "STORE_EXPERIANCE_DETAILS";
export const STORE_SKILLS_DETAILS = "STORE_SKILLS_DETAILS";
export const GET_ALL_DATA = "GET_ALL_DATA";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
